on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  test:
    name: test-py
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: test starting
        run: 
          bash docker-build-pytest.sh && bash docker-run-pytest.sh
