on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  remove:
    name: remove image and container
    runs-on: self-hosted
    steps:
      - name: remove image
        run: docker rmi pytest:1.0

      - name: remove container
        run: docker rm -f pytest
  
  build:
    name: build docker image
    needs: remove
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build image
        run: bash scripts/docker-build-pytest.sh
  test:   
    name: run pytest
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: start test
        run: bash scripts/docker-run-pytest.sh
